databases:
  - name: simple_form_bootstrap
    databaseName: simple_form_bootstrap
    user: simple_form_bootstrap

services:
  - type: web
    name: simple_form_bootstrap
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: simple_form_bootstrap
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false