name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install SQLite
      run: sudo apt-get install libsqlite3-dev
    - name: Build
      run: |
        gem install bundler
        bundle install --without production --jobs 4 --retry 3
    - name: Test
      run: bundle exec rake test
