name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true
    - name: Install SQLite
      run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
    - name: Test
      run: bundle exec rake test
      env:
        PARALLEL_WORKERS: 1
